"""kit_delta.py: compute (and assemble) the patch between two kit builds.

WHY THIS EXISTS. The kit is ~57 GiB, 53 of which is one unchanged model blob,
and there is no network path between the build box and the drive. Shipping the
logical delta instead of the whole tree turns an 80 GB cloud round trip into
~31 MB. That is only safe if the patch is PROVABLY complete, and a hand-written
file list is not: miss one changed file and the drive carries a kit that does
not match its own signed manifest.

So the patch is derived from the two manifests, not from judgement:

  every artifact in the NEW manifest whose sha256 differs from the OLD
  manifest's (or which the OLD manifest does not list) goes in the patch;
  every other artifact is already on the drive with exactly the right bytes.

`verify-kit` on the drive afterwards re-hashes all of them against the signed
manifest, so a missed or corrupted file fails there. This tool decides WHAT to
move; verify-kit remains the gate that decides whether the move worked.

Two things it also catches, both of which would break a patch-style copy:

  REMOVED artifacts. A patch copy cannot express a deletion, and a leftover
  file on the drive fails verify-kit's no-unlisted-files audit. If the diff
  reports removals, they must be deleted on the drive by hand (the tool prints
  the list) or the sync has to be a full mirror instead.

  The UNSIGNED root files. launch.sh / PREREQS.txt / the console pair sit
  OUTSIDE kit/ and appear in no manifest, so a manifest diff cannot see them.
  They are ALWAYS copied into the patch: BP46's Fix 3 lives in launch.sh, and
  verify-kit structurally cannot tell you whether it arrived.

USAGE, on the build box:

  # BEFORE the rebuild, snapshot the manifest of what the drive holds today.
  # make-kit converges IN PLACE over the staging cache, so this is the only
  # chance to capture it.
  python kit_delta.py snapshot --kit <staging>/decant.Source/kit --out old_manifest.json

  # AFTER make-kit + make-ssd, report the delta (the "know before you move" gate)
  python kit_delta.py report --old old_manifest.json --new <staging>/decant.Source/kit/manifest.json

  # then assemble a patch folder shaped exactly like the SSD root
  python kit_delta.py assemble --old old_manifest.json --ssd-root <staging> --out <drive-folder>/kh-patch
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

# Files that live at the SSD root / inside decant.Source but in NO manifest.
# Regenerated by `khctl make-ssd`, unsigned by design, invisible to verify-kit,
# and the home of Fix 3. Always in the patch, never diffed.
UNSIGNED_ROOT_FILES = ("launch.sh", "PREREQS.txt", "console.sh",
                       "Open Console.desktop")
NESTED_DIR = "decant.Source"


def _artifacts(manifest_path: Path) -> dict[str, str]:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    return {a["path"]: a["sha256"] for a in data.get("artifacts", [])}


def _sizes(manifest_path: Path) -> dict[str, int]:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    return {a["path"]: a.get("bytes", 0) for a in data.get("artifacts", [])}


def _version(manifest_path: Path) -> str:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    return data.get("package_version", "?")


def _human(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if abs(n) < 1024 or unit == "GB":
            return f"{n:.1f} {unit}" if unit != "B" else f"{n} B"
        n /= 1024.0
    return f"{n} B"


def diff(old: Path, new: Path) -> dict:
    old_hashes, new_hashes = _artifacts(old), _artifacts(new)
    new_sizes = _sizes(new)
    added = sorted(p for p in new_hashes if p not in old_hashes)
    changed = sorted(p for p in new_hashes
                     if p in old_hashes and old_hashes[p] != new_hashes[p])
    removed = sorted(p for p in old_hashes if p not in new_hashes)
    unchanged = sorted(p for p in new_hashes
                       if p in old_hashes and old_hashes[p] == new_hashes[p])
    return {
        "old_version": _version(old), "new_version": _version(new),
        "added": added, "changed": changed, "removed": removed,
        "unchanged_count": len(unchanged),
        "move_bytes": sum(new_sizes.get(p, 0) for p in (*added, *changed)),
        "stay_bytes": sum(new_sizes.get(p, 0) for p in unchanged),
    }


def cmd_snapshot(args: argparse.Namespace) -> int:
    src = Path(args.kit) / "manifest.json"
    if not src.exists():
        print(f"no manifest at {src}", file=sys.stderr)
        return 2
    out = Path(args.out)
    shutil.copy2(src, out)
    print(f"snapshotted {_version(src)} manifest -> {out} "
          f"({len(_artifacts(src))} artifacts). Keep this until the sync is "
          f"verified on the drive.")
    return 0


def _report(d: dict, patch_extras: int) -> None:
    print(f"kit delta  {d['old_version']} -> {d['new_version']}")
    print("-" * 60)
    print(f"  added    {len(d['added']):5d}")
    print(f"  changed  {len(d['changed']):5d}")
    print(f"  removed  {len(d['removed']):5d}")
    print(f"  same     {d['unchanged_count']:5d}  ({_human(d['stay_bytes'])} "
          f"stays on the drive, never uploaded)")
    print("-" * 60)
    print(f"  TO MOVE: {_human(d['move_bytes'])} of signed kit artifacts "
          f"+ {patch_extras} unsigned root file(s)")
    for label in ("added", "changed"):
        if d[label]:
            print(f"\n  {label}:")
            for path in d[label]:
                print(f"    {path}")
    if d["removed"]:
        print("\n  !! REMOVED artifacts. A patch copy CANNOT delete these, and")
        print("     a leftover file on the drive FAILS verify-kit's no-unlisted")
        print("     audit. Delete each by hand on the drive, or sync as a full")
        print("     mirror instead:")
        for path in d["removed"]:
            print(f"    {path}")


def cmd_report(args: argparse.Namespace) -> int:
    _report(diff(Path(args.old), Path(args.new)), len(UNSIGNED_ROOT_FILES))
    return 0


def cmd_assemble(args: argparse.Namespace) -> int:
    """Build a patch folder shaped like the SSD root, so the drive-side copy
    is one overwriting overlay and cannot land a file in the wrong place."""
    ssd_root = Path(args.ssd_root).resolve()
    inner = ssd_root / NESTED_DIR
    kit = inner / args.kit_subdir
    new_manifest = kit / "manifest.json"
    if not new_manifest.exists():
        print(f"no manifest at {new_manifest} (run make-kit first)",
              file=sys.stderr)
        return 2
    d = diff(Path(args.old), new_manifest)
    out = Path(args.out).resolve()
    out.mkdir(parents=True, exist_ok=True)

    copied = 0
    for rel in (*d["added"], *d["changed"]):
        src, dst = kit / rel, out / NESTED_DIR / args.kit_subdir / rel
        if not src.exists():
            print(f"manifest lists {rel} but it is not on disk", file=sys.stderr)
            return 1
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied += 1
    # The manifest + signature are never listed inside themselves, so the diff
    # cannot see them. They change on EVERY rebuild by definition.
    for rel in ("manifest.json", "manifest.json.minisig"):
        src = kit / rel
        if src.exists():
            dst = out / NESTED_DIR / args.kit_subdir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            copied += 1
        elif rel == "manifest.json.minisig":
            print("!! kit is UNSIGNED (no manifest.json.minisig). Do not ship "
                  "it: sign it first (the org ceremony), then re-assemble.",
                  file=sys.stderr)
            return 1
    # Unsigned, invisible to verify-kit, and where Fix 3 lives.
    extras = 0
    for name in UNSIGNED_ROOT_FILES:
        src = inner / name
        if src.exists():
            dst = out / NESTED_DIR / name
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            extras += 1
        else:
            print(f"!! {name} missing at {inner}: did `khctl make-ssd` run?",
                  file=sys.stderr)
            return 1
    for shortcut in ssd_root.glob("Launch *.desktop"):
        shutil.copy2(shortcut, out / shortcut.name)
        extras += 1

    total = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    _report(d, extras)
    print("-" * 60)
    print(f"patch assembled at {out}")
    print(f"  {copied} signed kit file(s) + {extras} unsigned root file(s), "
          f"{_human(total)} on disk")
    print(f"  layout mirrors the SSD root, so the drive-side step is ONE "
          f"overlay copy")
    print()
    print("On the ROG, AFTER the patch folder is fully downloaded (real files,")
    print("not stream placeholders), overlay it onto the drive. Use /E, and")
    print("NEVER /MIR or /PURGE: this folder is a patch, and mirroring it")
    print("would purge the 53 GiB model store the patch deliberately omits.")
    print(r'  robocopy "<patch>" "D:\" /E /NP /R:2 /W:2')
    print()
    print("Then BOTH Step 4 checks, in order:")
    print(r'  khctl verify-kit --kit D:\decant.Source\kit')
    print(r"  Select-String -Path 'D:\decant.Source\launch.sh' "
          r"-Pattern 'cpython-3.12-','python3.12 -m venv'")
    print("  (expect a hit on cpython-3.12- and NO hit on python3.12 -m venv)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(required=True)

    p = sub.add_parser("snapshot", help="save the CURRENT kit manifest before "
                                       "a rebuild converges over it")
    p.add_argument("--kit", required=True)
    p.add_argument("--out", default="old_manifest.json")
    p.set_defaults(fn=cmd_snapshot)

    p = sub.add_parser("report", help="what the rebuild changed, and how many "
                                      "bytes actually have to travel")
    p.add_argument("--old", required=True)
    p.add_argument("--new", required=True)
    p.set_defaults(fn=cmd_report)

    p = sub.add_parser("assemble", help="copy exactly the changed files into a "
                                        "patch folder shaped like the SSD root")
    p.add_argument("--old", required=True)
    p.add_argument("--ssd-root", required=True,
                   help="the staging root holding decant.Source/")
    p.add_argument("--kit-subdir", default="kit")
    p.add_argument("--out", required=True, help="patch folder (in the synced "
                                                "Drive folder)")
    p.set_defaults(fn=cmd_assemble)

    args = parser.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
