"""Synthetic corpus generator (campaign phase) — grounded in public GMP
document research, generated by LOCAL models only (privacy fork intact).

See `.Progress Docs/Ongoing/KnowledgeHub_SyntheticCorpus_Spec_v0.1_2026-07-23.md`.

Two layers, mirroring the real pipeline:
  * SeedRegistry — a DETERMINISTIC, seeded backbone of entities (people,
    vendors, customers, products, materials, equipment, SOP numbers, forms)
    with the research's real ID formats. Pure code: no model, reproducible.
    This is what makes the corpus CONNECTED — every narrative doc references
    these IDs, so the same entity recurs across docs under varied surface
    forms (the entity-resolution target) and cross-doc chains exist for
    multi-hop retrieval.
  * NarrativeGenerator — a LOCAL Ollama model writes the PROSE for a
    structured brief the backbone hands it. IDs, references, supersession and
    the cross-reference graph are code-controlled (connectivity is not left to
    the model); only the wording is generated. Fictional throughout.

The tabular/SoR layer (master tables + logs as CSV) is pure code too, and
carries the deliberate ER noise (a vendor spelled two ways sharing a tax_id,
a lot number reused across vendors, an employee nicknamed across sheets).

CorpusSynthesizer.generate() writes files into a directory tree by track; the
real capture->process->extract->resolve pipeline ingests that tree via
FilesystemSourceAdapter (see scripts/build_corpus.py). Nothing here writes to
the DB directly — the pipeline owns that.
"""
from __future__ import annotations

import csv
import io
import json
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from knowledge_hub.config import settings

GENERATOR_VERSION = "0.1.0"

# --- domain vocabulary (fictional; structure from the public research) ------
COMPANY = "Diversified Botanics"
SITE = "SITE-NJ1"

_FIRST = ["Dana", "Priya", "Marcus", "Lena", "Tomas", "Aisha", "Ravi", "Nora",
          "Colin", "Yuki", "Sofia", "Ibrahim", "Greta", "Diego", "Hana",
          "Omar", "Freya", "Luis", "Mei", "Karl", "Ada", "Tariq", "Ines",
          "Paulo", "Zoe", "Nils", "Rania", "Vikram", "Elsa", "Bruno",
          "Clara", "Sven", "Amara", "Jonas", "Leila", "Pedro", "Rin", "Otto",
          "Vera", "Kojo"]
_LAST = ["Reyes", "Okafor", "Lindqvist", "Haddad", "Novak", "Mbeki", "Costa",
         "Tanaka", "Bauer", "Silva", "Petrov", "Nguyen", "Adeyemi", "Kaur",
         "Rossi", "Fischer", "Moreau", "Kim", "Santos", "Weber", "Dubois",
         "Ivanov", "Cohen", "Larsson", "Park"]
_ROLES = ["QA Reviewer", "QA Manager", "QC Analyst", "QC Manager",
          "Production Lead", "Manufacturing Supervisor", "Operator",
          "Warehouse Manager", "Maintenance Technician", "Validation Engineer",
          "Regulatory Affairs Manager", "Document Control Coordinator",
          "Training Coordinator", "Site Director", "Supplier Quality Engineer"]
_BOTANICALS = ["Ashwagandha", "Turmeric Curcumin", "Rhodiola", "Milk Thistle",
               "Valerian Root", "Ginkgo Biloba", "Echinacea", "Saw Palmetto",
               "Bacopa", "Elderberry", "Ginger Extract", "Green Tea Extract"]
_FORMS = ["Capsule", "Tablet", "Softgel", "Powder", "Liquid Extract"]
_ORG_SUFFIX = ["Inc", "LLC", "Corp", "Co", "Ltd", "Botanicals", "Labs",
               "Naturals", "Supply", "Group"]
_EQUIP = [("Blender", "BLND"), ("Tablet Press", "TAB-PRESS"),
          ("Fluid Bed Dryer", "FBD"), ("Mixer", "MIX"), ("Encapsulator", "ENC"),
          ("HPLC", "HPLC"), ("Balance", "BAL"), ("Coating Pan", "COAT"),
          ("Mill", "MILL"), ("Packaging Line", "PKG")]
_DEPTS = ["QA", "QC", "PROD", "WH", "ENG", "VAL", "REG"]
_SOP_TOPICS = [
    ("QA", "Deviation Management"), ("QA", "CAPA Management"),
    ("QA", "Batch Release and Disposition"), ("QA", "Document Control"),
    ("QA", "Change Control"), ("QA", "Product Recall"),
    ("QA", "Internal Audit"), ("QC", "Out-of-Specification Investigation"),
    ("QC", "Botanical Identity Testing"), ("QC", "HPLC Assay Operation"),
    ("PROD", "Batch Production Record Review"), ("PROD", "Line Clearance"),
    ("PROD", "Weighing and Dispensing"), ("PROD", "Yield Reconciliation"),
    ("ENG", "Equipment Cleaning"), ("ENG", "Preventive Maintenance"),
    ("VAL", "Cleaning Validation"), ("WH", "Material Receipt and Quarantine"),
    ("WH", "Label Reconciliation"), ("QC", "Stability Program"),
]


def _slug(text: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in text).strip("_")


# Per-source manifest declarations (folded into source_registry.config at
# ingest so the pipeline classifies each doc's track/doc_type deterministically
# instead of falling back to detection, and so SoR key columns become the
# strong `extracted_keys` the resolver's T0 tier matches on). Only ontology-
# BOUND predicates appear in `columns` (baseline-0.1 has no business
# predicates, so most SoR facts are left as keyed mentions — real ER positives
# without forcing quarantine); `reports_to` is bound, so it rides as a fact.
NARRATIVE_TRACKS = {  # folder -> doc_type (all data_track=prose so they chunk)
    "sop": "sop", "prose": "prose", "communication": "communication",
    "form": "form",
}
STRUCTURED_MAPS = {   # folder -> (doc_type, structured_map)
    "sor_employees": ("sor", {
        "entity_type": "Person", "subject_column": "full_name",
        "key_columns": {"employee_id": "employee_id", "email": "email"},
        "columns": {"reports_to": {"predicate": "reports_to",
                                   "object_entity_type": "Person"}}}),
    "sor_vendors": ("sor", {
        "entity_type": "Organization", "subject_column": "vendor_name",
        "key_columns": {"vendor_id": "vendor_id", "tax_id": "tax_id",
                        "email": "email"}}),
    "sor_customers": ("sor", {
        "entity_type": "Organization", "subject_column": "customer_name",
        "key_columns": {"customer_id": "customer_id", "tax_id": "tax_id"}}),
    "sor_products": ("sor", {
        "entity_type": "Asset", "subject_column": "product_name",
        "key_columns": {"product_code": "product_code"}}),
    "sor_materials": ("sor", {
        "entity_type": "Asset", "subject_column": "material_name",
        "key_columns": {"material_id": "material_id"}}),
    "sor_equipment": ("sor", {
        "entity_type": "Asset", "subject_column": "equipment_name",
        "key_columns": {"equipment_id": "equipment_id"}}),
    # Logs: structured track, keyed mentions only (no subject-per-row identity
    # worth a map) -> doc_type tabular, no structured_map.
    "tabular_cleaning": ("tabular", None),
    "tabular_receipts": ("tabular", None),
}


# ---------------------------------------------------------------------------
# Deterministic seed registry — the connected backbone
# ---------------------------------------------------------------------------
@dataclass
class Registry:
    employees: list[dict] = field(default_factory=list)
    vendors: list[dict] = field(default_factory=list)
    customers: list[dict] = field(default_factory=list)
    products: list[dict] = field(default_factory=list)
    materials: list[dict] = field(default_factory=list)
    equipment: list[dict] = field(default_factory=list)
    sops: list[dict] = field(default_factory=list)
    forms: list[dict] = field(default_factory=list)
    er_noise: list[dict] = field(default_factory=list)  # planted hard cases


SCALES = {
    # (employees, vendors, customers, products, materials, equipment, sops,
    #  narrative docs per track: sop, prose, comms, forms)
    # Retrieval tracks are prose/sop/communication (ratified 2026-07-23: form/
    # tabular/sor are STRUCTURED surfaces feeding ER + extraction, not
    # retrieval). Comms are short (~2 child chunks each), so their count runs
    # high — and ~every 3rd thread gets a reply message — to clear the
    # >=50-queries floor with margin.
    "pilot": dict(emp=8, ven=6, cus=6, prod=4, mat=6, equip=6, sop=3,
                  n_sop=3, n_prose=1, n_comm=3, n_form=3),
    "full": dict(emp=40, ven=35, cus=35, prod=12, mat=30, equip=20, sop=20,
                 n_sop=20, n_prose=15, n_comm=40, n_form=24),
}

# Prose-track variety: each policy/manual doc gets its own topic so 15 prose
# docs aren't 15 near-identical quality manuals.
_POLICY_TOPICS = [
    "Quality Management System overview", "Quality Policy statement",
    "Supplier qualification program", "Training and personnel qualification",
    "Data integrity and documentation practices", "Sanitation program",
    "Product recall program", "Complaint handling program",
    "Environmental monitoring program", "Stability program overview",
    "Change management philosophy", "Risk management approach",
    "Internal audit program", "Botanical identity assurance program",
    "Warehouse and distribution controls",
]


class SeedRegistry:
    def __init__(self, seed: int = 20260723):
        self._rng = random.Random(seed)

    def build(self, scale: str) -> Registry:
        s = SCALES[scale]
        rng = self._rng
        reg = Registry()

        # People with a reports_to tree (roots = Site Director).
        for i in range(s["emp"]):
            role = _ROLES[i % len(_ROLES)]
            reg.employees.append({
                "employee_id": f"EMP-{10000 + i}",
                "full_name": f"{rng.choice(_FIRST)} {rng.choice(_LAST)}",
                "role": role,
                "email": None,          # filled after name known, below
                "reports_to": None,
                "site": SITE,
            })
        for e in reg.employees:
            first, last = e["full_name"].split(" ", 1)
            e["email"] = f"{first[0].lower()}{_slug(last).lower()}@diversifiedbotanics.example"
        directors = [e for e in reg.employees if e["role"] == "Site Director"] \
            or reg.employees[:1]
        for e in reg.employees:
            if e not in directors:
                e["reports_to"] = rng.choice(directors)["employee_id"]

        # Vendors + customers (Organizations, high-stakes ER).
        for i in range(s["ven"]):
            base = f"{rng.choice(_LAST)} {rng.choice(_ORG_SUFFIX)}"
            reg.vendors.append({
                "vendor_id": f"SUP-{1000 + i}", "vendor_name": base,
                "tax_id": f"{rng.randint(10, 99)}-{rng.randint(1000000, 9999999)}",
                "email": f"quality@{_slug(base).lower()}.example",
                "qualification_status": rng.choice(["Approved", "Conditional"]),
            })
        for i in range(s["cus"]):
            base = f"{rng.choice(_LAST)} {rng.choice(_ORG_SUFFIX)}"
            reg.customers.append({
                "customer_id": f"CUST-{2000 + i}", "customer_name": base,
                "tax_id": f"{rng.randint(10, 99)}-{rng.randint(1000000, 9999999)}",
                "customer_type": rng.choice(["Wholesale", "Retail", "Contract"]),
            })

        # Products, materials (with vendor links), equipment.
        for i in range(s["prod"]):
            bot = _BOTANICALS[i % len(_BOTANICALS)]
            form = rng.choice(_FORMS)
            strength = rng.choice([250, 300, 500, 600, 1000])
            reg.products.append({
                "product_code": f"FG-{4000 + i}",
                "product_name": f"{bot} {strength}mg {form}",
                "botanical": bot, "strength_mg": strength, "form": form,
            })
        for i in range(s["mat"]):
            bot = _BOTANICALS[i % len(_BOTANICALS)]
            vendor = rng.choice(reg.vendors)
            reg.materials.append({
                "material_id": f"BOT-{5000 + i}",
                "material_name": f"{bot} Extract (raw)",
                "lot_no": f"L{rng.randint(24, 26)}-{rng.randint(10000, 99999)}",
                "vendor_id": vendor["vendor_id"],
                "expiry": f"20{rng.randint(27, 29)}-{rng.randint(1,12):02d}-01",
            })
        for i in range(s["equip"]):
            name, code = _EQUIP[i % len(_EQUIP)]
            reg.equipment.append({
                "equipment_id": f"EQ-{code}-{i + 1:02d}",
                "equipment_name": name,
                "room_id": f"RM-{101 + (i % 6)}",
            })

        # SOPs with supersession chains (some Rev 02 supersede Rev 01).
        topics = _SOP_TOPICS[:s["sop"]]
        for i, (dept, title) in enumerate(topics):
            rev = rng.choice([1, 1, 2, 3])
            reg.sops.append({
                "sop_no": f"SOP-{dept}-{i + 1:03d}",
                "title": title, "dept": dept, "version": f"Rev {rev:02d}",
                "supersedes": f"Rev {rev - 1:02d}" if rev > 1 else None,
            })
        # Form templates.
        for fno, name in [("QA-035", "Deviation Report"),
                          ("F-CAPA-002", "CAPA Form"),
                          ("QC-018", "Out-of-Specification Report"),
                          ("QMS-125", "Change Control Form"),
                          ("ENG-051", "Equipment Cleaning Log"),
                          ("QA-060", "Batch Release Disposition"),
                          ("WH-022", "Supplier Corrective Action Request"),
                          ("PROD-041", "Batch Production Record")]:
            reg.forms.append({"form_no": fno, "form_name": name})

        self._plant_er_noise(reg, rng)
        return reg

    def _plant_er_noise(self, reg: Registry, rng: random.Random) -> None:
        """Deliberate hard cases (spec §1.4): the entities ER must get right."""
        if reg.vendors:
            v = reg.vendors[0]
            # Same org, two surface forms, SAME tax_id -> a match that name
            # similarity alone might miss / a key must catch.
            variant = v["vendor_name"].upper().replace(" INC", "").replace(
                " LLC", "")
            reg.er_noise.append({
                "kind": "org_variant_same_key", "entity": v["vendor_id"],
                "surface_a": v["vendor_name"], "surface_b": variant,
                "shared_key": {"tax_id": v["tax_id"]}, "match": True})
        if len(reg.vendors) >= 2:
            # Two DIFFERENT vendors reusing one supplier lot_no -> proves
            # lot_no alone is a weak key (hard negative).
            reg.er_noise.append({
                "kind": "shared_lot_diff_vendor",
                "entity_a": reg.vendors[0]["vendor_id"],
                "entity_b": reg.vendors[1]["vendor_id"],
                "shared_key": {"lot_no": "L25-40000"}, "match": False})
        if reg.employees:
            e = reg.employees[0]
            first, last = e["full_name"].split(" ", 1)
            reg.er_noise.append({
                "kind": "person_nickname_same_email", "entity": e["employee_id"],
                "surface_a": e["full_name"],
                "surface_b": f"{first[:3]}. {last}",
                "shared_key": {"email": e["email"]}, "match": True})


# ---------------------------------------------------------------------------
# Narrative generation (local model writes prose for a code-built brief)
# ---------------------------------------------------------------------------
_SOP_SECTIONS = ["Purpose", "Scope", "Responsibilities", "Definitions",
                 "Procedure", "References", "Revision History"]


class NarrativeGenerator:
    def __init__(self, model: Optional[str] = None, host: Optional[str] = None):
        import ollama
        self.model = model or settings.extraction_model
        self._client = ollama.Client(host=host or settings.ollama_host)

    def _write(self, instruction: str, max_words: int = 180) -> str:
        # Retry transient serving errors (a llama-server hiccup mid-way must
        # not kill a 40-minute full-scale generation run).
        import time as _time
        last: Exception | None = None
        for attempt in range(3):
            try:
                resp = self._client.chat(
                    model=self.model,
                    messages=[{"role": "user", "content": instruction}],
                    think=False, options={"temperature": 0.4})
                return resp.message.content.strip()
            except Exception as e:
                last = e
                _time.sleep(5 * (attempt + 1))
        raise RuntimeError(f"narrative generation failed after retries: {last}")

    # -- SOP: code owns the skeleton + refs; model writes each section's prose
    def sop(self, sop: dict, reg: Registry, rng: random.Random) -> str:
        equip = rng.choice(reg.equipment) if reg.equipment else None
        form = rng.choice(reg.forms) if reg.forms else None
        author = _pick_role(reg, "QA Reviewer", rng)
        approver = _pick_role(reg, "QA Manager", rng)
        refs = [s["sop_no"] for s in rng.sample(
            reg.sops, min(2, len(reg.sops))) if s["sop_no"] != sop["sop_no"]]

        lines = [f"# {sop['sop_no']} — {sop['title']}", "",
                 f"**Document number:** {sop['sop_no']}  ",
                 f"**Version:** {sop['version']}  ",
                 f"**Site:** {COMPANY}, {SITE}  ",
                 f"**Prepared by:** {author['full_name']} ({author['role']})  ",
                 f"**Approved by:** {approver['full_name']} ({approver['role']})  "]
        if sop["supersedes"]:
            lines.append(f"**Supersedes:** {sop['supersedes']}  ")
        lines.append("")

        brief = (f"You are writing a fictional GMP Standard Operating Procedure "
                 f"for {COMPANY}, a botanical supplement manufacturer. SOP "
                 f"{sop['sop_no']}, titled '{sop['title']}'. Write ONLY the "
                 f"body text of the '%s' section — no heading, no preamble, "
                 f"realistic GMP wording, concise.")
        for sec in _SOP_SECTIONS:
            lines.append(f"## {sec}")
            if sec == "References":
                lines.append(f"- 21 CFR Part 111")
                for r in refs:
                    lines.append(f"- {r}")
                if form:
                    lines.append(f"- Form {form['form_no']} ({form['form_name']})")
                lines.append("")
            elif sec == "Revision History":
                lines.append(f"- {sop['version']} — current effective version.")
                if sop["supersedes"]:
                    lines.append(f"- {sop['supersedes']} — superseded by "
                                 f"{sop['version']}.")
                lines.append("")
            elif sec == "Responsibilities":
                extra = (f" Mention that the {author['role']} prepares and the "
                         f"{approver['role']} approves this procedure.")
                lines.append(self._write(brief % sec + extra))
                lines.append("")
            elif sec == "Procedure" and equip:
                extra = (f" The procedure involves equipment {equip['equipment_id']} "
                         f"({equip['equipment_name']}) in room {equip['room_id']}. "
                         f"Use numbered steps.")
                lines.append(self._write(brief % sec + extra, max_words=260))
                lines.append("")
            else:
                lines.append(self._write(brief % sec))
                lines.append("")
        return "\n".join(lines)

    # -- Communication thread (deviation / release / recall ...)
    def comm(self, kind: str, reg: Registry, rng: random.Random,
             record_id: str) -> str:
        prod = rng.choice(reg.products)
        batch = f"B-2026-{rng.randint(1000, 9999)}"
        sender = rng.choice(reg.employees)
        recipient = _pick_role(reg, "QA Manager", rng)
        sop = rng.choice(reg.sops)
        subjects = {
            "deviation": f"[DEVIATION] {record_id} — {batch} {prod['product_name']} — investigation",
            "release": f"[BATCH RELEASE] {record_id} — {prod['product_code']} {batch} — DISPOSITION",
            "capa": f"[CAPA ASSIGNMENT] {record_id} — action owner assignment",
            "recall": f"[URGENT — RECALL] {prod['product_code']} affected lots",
            "audit": f"[AUDIT FINDING] {record_id} — response required",
        }
        subject = subjects.get(kind, f"[{kind.upper()}] {record_id}")
        instruction = (
            f"Write a SHORT fictional internal email (5-8 sentences) at {COMPANY}, "
            f"a botanical supplement maker. Type: {kind}. It concerns record "
            f"{record_id}, product {prod['product_name']} ({prod['product_code']}), "
            f"batch {batch}, and references procedure {sop['sop_no']}. From "
            f"{sender['full_name']} ({sender['role']}) to {recipient['full_name']} "
            f"({recipient['role']}). Realistic GMP quality tone. No signature block.")
        body = self._strip_headers(self._write(instruction, max_words=200))
        return (f"From: {sender['full_name']} <{sender['email']}>\n"
                f"To: {recipient['full_name']} <{recipient['email']}>\n"
                f"Subject: {subject}\n\n{body}\n")

    def comm_thread(self, kind: str, reg: Registry, rng: random.Random,
                    record_id: str, with_reply: bool) -> list[str]:
        """A thread: the original message, plus (optionally) the recipient's
        reply — same record id anchor, RE: subject, roles swapped."""
        original = self.comm(kind, reg, rng, record_id)
        if not with_reply:
            return [original]
        # Parse the envelope we own to swap the parties.
        head = dict(line.split(": ", 1) for line in
                    original.splitlines()[:3])
        reply_instruction = (
            f"Write a SHORT fictional reply email (3-5 sentences) in a GMP "
            f"quality thread at {COMPANY}. You are {head['To']} responding to "
            f"{head['From']} about record {record_id} ({kind}). Acknowledge, "
            f"state the decision or next step (e.g. investigation opened, "
            f"disposition, action owner assigned), and give a deadline. "
            f"No signature block.")
        body = self._strip_headers(self._write(reply_instruction, max_words=140))
        reply = (f"From: {head['To']}\nTo: {head['From']}\n"
                 f"Subject: RE: {head['Subject']}\n\n{body}\n")
        return [original, reply]

    @staticmethod
    def _strip_headers(body: str) -> str:
        # The model sometimes re-emits its own "Subject:"/"From:" header lines
        # inside the body; strip leading header-ish lines so we own the envelope.
        body_lines = body.splitlines()
        while body_lines and body_lines[0].split(":", 1)[0].strip().lower() in (
                "subject", "from", "to", "date", "re"):
            body_lines.pop(0)
        return "\n".join(body_lines).strip()

    # -- Completed form instance (header fields + model free-text body)
    def form(self, template: dict, reg: Registry, rng: random.Random,
             record_id: str) -> str:
        prod = rng.choice(reg.products)
        batch = f"B-2026-{rng.randint(1000, 9999)}"
        equip = rng.choice(reg.equipment)
        raised = rng.choice(reg.employees)
        sop = rng.choice(reg.sops)
        lines = [f"# {template['form_name']} — {record_id}", "",
                 f"**Form number:** {template['form_no']}  ",
                 f"**Record ID:** {record_id}  ",
                 f"**Product:** {prod['product_name']} ({prod['product_code']})  ",
                 f"**Batch/Lot:** {batch}  ",
                 f"**Equipment:** {equip['equipment_id']} ({equip['equipment_name']})  ",
                 f"**Raised by:** {raised['full_name']} ({raised['role']})  ",
                 f"**Governing SOP:** {sop['sop_no']}  ", ""]
        instruction = (
            f"Write the fictional narrative body of a GMP '{template['form_name']}' "
            f"at {COMPANY}. Record {record_id}, product {prod['product_name']}, "
            f"batch {batch}, equipment {equip['equipment_id']}. 4-6 sentences: "
            f"describe the event/observation, immediate action, and disposition. "
            f"Realistic quality wording.")
        lines.append("## Description")
        lines.append(self._write(instruction, max_words=200))
        return "\n".join(lines)

    # -- Quality policy / manual prose (per-topic, so 15 docs aren't clones)
    def policy(self, reg: Registry, rng: random.Random,
               topic: str = "Quality Management System overview") -> str:
        sops = rng.sample(reg.sops, min(4, len(reg.sops)))
        ref_list = "; ".join(f"{s['sop_no']} ({s['title']})" for s in sops)
        instruction = (
            f"Write a fictional one-page policy document for {COMPANY}, a "
            f"botanical supplement manufacturer, on the topic: '{topic}' "
            f"(3-4 short paragraphs). Reference these procedures by number "
            f"where relevant: {ref_list}. Narrative prose, not step-by-step. "
            f"Realistic GMP tone.")
        return (f"# {COMPANY} — {topic}\n\n"
                + self._write(instruction, max_words=350))


def _pick_role(reg: Registry, role: str, rng: random.Random) -> dict:
    matches = [e for e in reg.employees if e["role"] == role]
    return rng.choice(matches) if matches else rng.choice(reg.employees)


# ---------------------------------------------------------------------------
# Tabular / SoR emitters (pure code; carry the ER keys + planted noise)
# ---------------------------------------------------------------------------
def _csv(headers: list[str], rows: list[list[Any]]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(headers)
    w.writerows(rows)
    return buf.getvalue()


class TabularEmitter:
    def sor_tables(self, reg: Registry) -> dict[str, str]:
        """folder_name -> csv content (one master table per source folder, so
        each can carry its own structured_map via source_registry.config)."""
        return {
            "sor_employees": _csv(
                ["employee_id", "full_name", "role", "email", "reports_to", "site"],
                [[e["employee_id"], e["full_name"], e["role"], e["email"],
                  e["reports_to"] or "", e["site"]] for e in reg.employees]),
            "sor_vendors": _csv(
                ["vendor_id", "vendor_name", "tax_id", "email", "qualification_status"],
                [[v["vendor_id"], v["vendor_name"], v["tax_id"], v["email"],
                  v["qualification_status"]] for v in reg.vendors]),
            "sor_customers": _csv(
                ["customer_id", "customer_name", "tax_id", "customer_type"],
                [[c["customer_id"], c["customer_name"], c["tax_id"],
                  c["customer_type"]] for c in reg.customers]),
            "sor_products": _csv(
                ["product_code", "product_name", "botanical", "strength_mg", "form"],
                [[p["product_code"], p["product_name"], p["botanical"],
                  p["strength_mg"], p["form"]] for p in reg.products]),
            "sor_materials": _csv(
                ["material_id", "material_name", "lot_no", "vendor_id", "expiry"],
                [[m["material_id"], m["material_name"], m["lot_no"], m["vendor_id"],
                  m["expiry"]] for m in reg.materials]),
            "sor_equipment": _csv(
                ["equipment_id", "equipment_name", "room_id"],
                [[e["equipment_id"], e["equipment_name"], e["room_id"]]
                 for e in reg.equipment]),
        }

    def logs(self, reg: Registry, rng: random.Random) -> dict[str, str]:
        out = {}
        # Equipment cleaning log — rows reference equipment + operators.
        rows = []
        for i in range(max(12, len(reg.equipment) * 2)):
            eq = rng.choice(reg.equipment)
            op = rng.choice(reg.employees)
            ver = rng.choice(reg.employees)
            prod = rng.choice(reg.products)
            rows.append([f"2026-0{rng.randint(1,9)}-{rng.randint(10,28)}",
                         eq["equipment_id"], eq["equipment_name"],
                         prod["product_code"], f"B-2026-{rng.randint(1000,9999)}",
                         "Cleaning", op["employee_id"], ver["employee_id"],
                         "Clean"])
        out["tabular_cleaning"] = _csv(
            ["log_date", "equipment_id", "equipment_name", "product_code",
             "batch_lot_no", "activity_type", "done_by", "verified_by",
             "status"], rows)
        # Material receipt log — references vendor + material lots.
        rows = []
        for i, m in enumerate(reg.materials):
            rows.append([f"GRN-2026-{800 + i:05d}", m["material_id"],
                         m["material_name"], m["lot_no"], m["vendor_id"],
                         f"PO-2026-{1100 + i:05d}", "Released", m["expiry"]])
        out["tabular_receipts"] = _csv(
            ["grn_no", "material_id", "material_name", "material_lot_no",
             "vendor_id", "po_number", "qc_status", "expiry_date"], rows)
        return out


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------
class CorpusSynthesizer:
    def __init__(self, seed: int = 20260723, model: Optional[str] = None,
                 host: Optional[str] = None):
        self._seed = seed
        self._reg_builder = SeedRegistry(seed)
        self._narrator = NarrativeGenerator(model, host)
        self._tabular = TabularEmitter()

    def generate(self, out_dir: str | Path, scale: str = "pilot") -> dict:
        out = Path(out_dir)
        rng = random.Random(self._seed + 1)
        reg = self._reg_builder.build(scale)
        s = SCALES[scale]
        manifest: dict[str, Any] = {
            "company": COMPANY, "site": SITE, "scale": scale, "seed": self._seed,
            "generator_version": GENERATOR_VERSION, "model": self._narrator.model,
            "counts": {}, "sources": {}, "registry_sizes": {
                "employees": len(reg.employees), "vendors": len(reg.vendors),
                "customers": len(reg.customers), "products": len(reg.products),
                "materials": len(reg.materials), "equipment": len(reg.equipment),
                "sops": len(reg.sops)},
            "er_noise": reg.er_noise,
        }

        def emit(folder: str, filename: str, content: str,
                 config: dict[str, Any]) -> None:
            d = out / folder
            d.mkdir(parents=True, exist_ok=True)
            (d / filename).write_text(content, encoding="utf-8")
            manifest["sources"][folder] = config  # source_registry.config

        # SoR master tables + logs (deterministic) -> one source folder each,
        # carrying its structured_map so key columns become extracted_keys.
        sor_files = self._tabular.sor_tables(reg)
        log_files = self._tabular.logs(reg, rng)
        for folder, content in {**sor_files, **log_files}.items():
            doc_type, smap = STRUCTURED_MAPS[folder]
            cfg: dict[str, Any] = {"data_track": "structured", "doc_type": doc_type}
            if smap:
                cfg["structured_map"] = smap
            emit(folder, f"{folder}.csv", content, cfg)
        manifest["counts"]["sor_tabular"] = len(sor_files) + len(log_files)

        # Narrative docs (local model) -> per-track folders, each declaring its
        # doc_type (data_track=prose so they chunk + embed for retrieval).
        prose_cfg = lambda dt: {"data_track": "prose", "doc_type": dt}
        n_sop = 0
        sop_dir = out / "sop"; sop_dir.mkdir(parents=True, exist_ok=True)
        for sop in reg.sops[:s["n_sop"]]:
            md = self._narrator.sop(sop, reg, rng)
            (sop_dir / f"{sop['sop_no']}_{_slug(sop['title'])}.md").write_text(
                md, encoding="utf-8")
            n_sop += 1
        manifest["counts"]["sop"] = n_sop
        if n_sop:
            manifest["sources"]["sop"] = prose_cfg("sop")

        prose_dir = out / "prose"; prose_dir.mkdir(parents=True, exist_ok=True)
        for i in range(s["n_prose"]):
            topic = _POLICY_TOPICS[i % len(_POLICY_TOPICS)]
            (prose_dir / f"policy_{i + 1:02d}_{_slug(topic)[:40]}.md").write_text(
                self._narrator.policy(reg, rng, topic), encoding="utf-8")
        manifest["counts"]["prose"] = s["n_prose"]
        if s["n_prose"]:
            manifest["sources"]["prose"] = prose_cfg("prose")

        comm_dir = out / "communication"; comm_dir.mkdir(parents=True, exist_ok=True)
        comm_kinds = ["deviation", "release", "capa", "recall", "audit",
                      "supplier"]
        n_msgs = 0
        for i in range(s["n_comm"]):
            kind = comm_kinds[i % len(comm_kinds)]
            rid = f"{kind[:3].upper()}-2026-{100 + i:04d}"
            messages = self._narrator.comm_thread(
                kind, reg, rng, rid, with_reply=(i % 3 == 0))
            for m_ix, message in enumerate(messages):
                name = f"{rid}.txt" if m_ix == 0 else f"{rid}_re{m_ix}.txt"
                (comm_dir / name).write_text(message, encoding="utf-8")
                n_msgs += 1
        manifest["counts"]["communication"] = n_msgs
        if s["n_comm"]:
            manifest["sources"]["communication"] = prose_cfg("communication")

        form_dir = out / "form"; form_dir.mkdir(parents=True, exist_ok=True)
        for i in range(s["n_form"]):
            template = reg.forms[i % len(reg.forms)]
            rid = f"{_slug(template['form_no'])}-INST-{i + 1:03d}"
            (form_dir / f"{rid}.md").write_text(
                self._narrator.form(template, reg, rng, rid), encoding="utf-8")
        manifest["counts"]["form"] = s["n_form"]
        if s["n_form"]:
            manifest["sources"]["form"] = prose_cfg("form")

        (out / "corpus_manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8")
        return manifest
